# Generated by Django 4.1.7 on 2023-03-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NotesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("note", models.TextField()),
                ("is_completed", models.BooleanField(default=False)),
                ("date", models.DateField(auto_now=True)),
                ("startTime", models.DateField(auto_now_add=True)),
                ("endTime", models.DateTimeField(auto_now_add=True)),
                ("color", models.IntegerField()),
                ("remind", models.BooleanField(default=False)),
                ("repeat", models.BooleanField(default=False)),
            ],
        ),
    ]
