# Generated by Django 4.1.7 on 2023-03-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notesmodel",
            name="color_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
